version: "2"

volumes:
  db-data:
    external: false

services:
  prod_db:
    image: postgres
    env_file: prod.env
    volumes:
      - db-data:/var/lib/postgresql/db-data

  prod_app:
    build: .
    env_file: prod.env
    ports:
      - "3000:3000"
    depends_on:
      - prod_db